### ISSUE TITLE
Claire to do for Thursday

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/GigPlatRevisit#1]
- Explore the [Google Drive](https://drive.google.com/drive/folders/11RPDIoHab8V6SZZyITvXGrXx548fX0lc?usp=sharing) linked off of the wiki 
- Complete the [Citi training](https://www.washington.edu/research/hsd/training/required-training/web-based-citi-training/) for doing human subject research at UW 
- Let Nic know when above is complete so he can add you to the IRB document

**Comment by cmcd276** [comment]
@nniiicc should my focus group transcript notes be an analytical memo, or just quotes and informal thoughts?

**Comment by nniiicc** [comment]
The former - memo - would be preferrable ... You should think of this as arranging your thoughts / impressions for future systematic analysis of the transcripts
