### ISSUE TITLE
Informed consent form

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/GigPlatRevisit#11]
Hi Nic--

A reminder to please send me the informed consent form to attach to the follow-up emails. Thanks!

**Comment by nniiicc** [comment]
I have uploaded this to the repository https://github.com/BITS-Research/GigPlatRevisit/blob/master/GigPlat-Consent-06152021.docx - please add this to the working dropbox documentation and link to it in the Wiki so we have this archived for the future
