### ISSUE TITLE
Revised recruitment emails

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/GigPlatRevisit#13]
Two email scripts to develop:
1. Follow up email to Summer 2020 participants
2. Initial recruitment to Focus Group 2020 participants

**Comment by thin-lizard** [comment]
Hi Nic-- please see the drafted scripts [here](https://docs.google.com/document/d/1qpzSzUIDS9pDWi1YedAjouj4cs7SFlkUtdxLEb0UlGg/edit)

**Comment by nniiicc** [comment]
I slightly tweaked the subject line of the first email (re-contacting 2020 pool)- but this looks great - please go ahead and send. 

Let's wait one more day to see if this reminder encourages any more responses - then send the recruitment message to 2019/20 pool. (This email also looks great - nothing to add to this).
