### ISSUE TITLE
smart cities reading

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/GigPlatRevisit#17]
Hi Nic--

A reminder as discussed- please send me any recommended readings on smart cities. Thanks!

**Comment by nniiicc** [comment]
A few recommendations:
- This is a good primer / overview https://mitpress.mit.edu/books/smart-cities (if you want to "download" you can find a copy here http://libgen.is/search.php?req=smart+cities+Germaine+Halegoua&open=0&res=25&view=simple&phrase=1&column=def ) 
- I like this article thinking about smart cities as a failed concept -  Sadowski, J., & Bendor, R. (2019). Selling smartness: Corporate narratives and the smart city as a sociotechnical imaginary. Science, Technology, & Human Values, 44(3), 540-563.  https://journals.sagepub.com/doi/pdf/10.1177/0162243918806061? 
- And Bianca Wylie is usually a good read on all things smart and civic tech Wylie, B. (2018). Searching for the smart city's democratic future. Centre for International Governance Innovation, 13. https://www.cigionline.org/articles/searching-smart-citys-democratic-future/
