### ISSUE TITLE
Consolidate interview data

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/GigPlatRevisit#18]
Create an overview (readme) of data sets we have 

- # of participants 
- time frame 

Add to in-take form... 
- previous interview (appoximate date Fall 2019, Summer 2020)
- locale (Seattle region or not - if not the approximate region or city)

**Comment by thin-lizard** [comment]
I added locale and prev. interview/focus group info for participants we interviewed together, and those I interviewed alone-- [[here]](https://www.dropbox.com/scl/fi/whrzsl5bo5g2o8o5nx3om/2021-Gigplat-revisit_scheduled-interviews.xlsx?dl=0&rlkey=num7faz9rehw19aons5qdew21)

- There are two interviews where I didn't confirm (my mistake)- I'm double-checking with the 2019 spreadsheets & transcripts to see if it's clear
- I highlighted in red two of your interviews that I believe are missing from the Dropbox, with tentative IDs based on two empty folders
- We're also missing a gift card link for a completed interview- I'm checking to see if I have a previous version of the spreadsheet with that info saved
