### ISSUE TITLE
Week of 6/22/2020

### ISSUE THREAD

**Issue by cmcd276** [BITS-Research/GigPlatRevisit#2]
### 6/25/2020 
looked through gig worker project repository, read over github use guide, read grant application, browsed materials on 01 GigPlat team drive (1hr)
meeting w nic, reading four transcripts from focus group interviews, first draft of analytical memo (7.5hr.) 

### 6/26/2020
completed research with human subjects training (2hr.)
redrafting analytical memo on focus group transcripts (2hr.)

incompleted planned tasks: analytical memo of focus group transcripts (second draft in progress)
upcoming planned tasks: finish analytical memo, get next set of directions from nic

12.5 hours total @nniiicc

**Comment by nniiicc** [comment]
Human subject training does not count as paid hours
