### ISSUE TITLE
Wave 3 Results - JASIST Paper

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/GigPlatRevisit#31]
Put link to draft and updates here

**Comment by thin-lizard** [comment]
- [skeleton](https://docs.google.com/document/d/1z-e6dvZFMgGrUddyTlarbMyoyb5gNPnzDCkp6m5hPxs/edit)

**Comment by thin-lizard** [comment]
[Abstract + outline](https://docs.google.com/document/d/1PYRAwAUeJTvjnWewFEEXoHceq1O7O4TN4Ahux30o1_I/edit#)

**Comment by thin-lizard** [comment]
"Policy legibility"
- [outline](https://docs.google.com/document/d/18whfu12pdLG5O-RUpKq3WIKrx7hhHOVA87X1zoC19uI/edit)
- background [skeleton](https://docs.google.com/document/d/1UCdU942a5cOMpoznQ9uJhuzAKC2eLO9VpKBaEINxj8Q/edit#) - precarity at 3 levels & Seattle backdrop
- [LS memo](https://docs.google.com/document/d/1RNYm-Sx-Ssucj-AxL5vQoKZFSVTUAWmHnGJXJuRVy84/edit#)

**Comment by thin-lizard** [comment]
Outline/draft #? -- this time is the charm: https://docs.google.com/document/d/1x--HPQmnsNDkdtSSD1r-TIecOOpeNo-LunwySpDhhtE/edit#

**Comment by thin-lizard** [comment]
Paper draft  10.07 - [no comments](https://docs.google.com/document/d/1OkPc_-kB3OSAHk-JSeOS_mQQbAhty641nLUrslH1l6E/edit#heading=h.y4gxymfehfjq) - fullest draft, minus conclusion and citations; shared with lab

Paper draft 07.20- [with comments](https://docs.google.com/document/d/1x--HPQmnsNDkdtSSD1r-TIecOOpeNo-LunwySpDhhtE/edit#) - includes comments on structure, alt. phrasing, citations

[GigPlat Open Questions](https://docs.google.com/document/d/1xU28JlF5bXV32FnX7rj4pCfkNUULzbXvOU_xMlszX_c/edit) - NW memo on structure

**Comment by thin-lizard** [comment]
Revisiting transcripts: https://docs.google.com/spreadsheets/d/1K9J7f1V-ZKrb9FTVQQhr0GI1yGHqVUq8W7cGEyihIcY/edit#gid=0

**Comment by thin-lizard** [comment]
@lindseysschwartz  - motivate the interpretations, and place them back in the findings section --> 
	conjecture, how often we saw it, and then substantiate

**Comment by thin-lizard** [comment]
@nniiicc -- reiterating the message I sent in slack - I built out the findings section of the gigplat paper -- see [here](https://docs.google.com/document/d/1x--HPQmnsNDkdtSSD1r-TIecOOpeNo-LunwySpDhhtE/edit#) --  but it definitely needs to be pared down. I plan to edit a hard copy to restructure the argument when I have fresh eyes. If you look it over before monday, what would be most helpful is highlighting points to elaborate on and points to exclude. I left comments around a few excerpts that may fit in. if they don’t, we’ve got them for later. thank you again!

**Comment by nniiicc** [comment]
👍

**Comment by thin-lizard** [comment]
Current draft: https://docs.google.com/document/d/1yPMgkbUPmcE0X1vKeEA560QxLcdTDUtRBXeidx0WaWc/edit#

To dos
- [x] Write a reverse outline from the draft (including an unwritten discussion / conclusion section)
- [ ] Clarify "contributions" vs "implications" vs "findings"
    - Set up the contribution and implications in the Introduction in short sentences
    - The expand upon these contributions, tying back to the findings, in the Conclusion section
 
Other notes:
- [ ] Make consistent the dates (2019-2022); as well as things like “three years” 
- [x] Explain Design vs Implementation of policy  
    - Policy is hard to design because of compensation structure
    - Difference bw roles of City Council and OLS
    - We describe implementation in the findings section, but need to summarize design beforehand
- [x] Legislation vs regulation vs policy vs municipal ordiance
- [x] Table for the policies in Seattle
- [x] In the background - under explaining regulation - talking about why this is so hard to design - what are you rewarding, per task, per mile, or per minute...
- [x] include Uber / Lyft fined by Seattle
- [ ] Sentiment section needs transition from Policy Access
- [x] Sentiment section streamlined...
- [ ] Reverse engineer the finding section from the “implications of findings” (from 07/20 draft)
