### ISSUE TITLE
Qualitative Insights for Gig Work Regulation

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/GigPlatRevisit#33]
Das Acevedo, D. (Ed.). (2020). _Beyond the Algorithm: Qualitative Insights for Gig Work Regulation_. Cambridge: Cambridge University Press. doi:10.1017/9781108767910

**Comment by thin-lizard** [comment]
- 1[The Rise and Scope of Gig Work Regulation](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-1/type/BOOK_PART#CN-bp-1)Deepa Das Acevedo
- 2[An Uber Ambivalence](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-2/type/BOOK_PART#CN-bp-2)Employee Status, Worker Perspectives, and Regulation in the Gig EconomyV. B. Dubal
- 3[Invisible Work, Visible Workers](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-3/type/BOOK_PART#CN-bp-3)Visibility Regimes in Online Platforms for Domestic WorkAlexandra Mateescu and Julia Ticona
- 4[The Importance of Qualitative Research Approaches to Gig Economy Taxation](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-4/type/BOOK_PART#CN-bp-4)Shu-Yi Oei and Diane M. Ring
- 5[Just a Gig?](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-5/type/BOOK_PART#CN-bp-5)Sharing Economy Work and the Implications for Career TrajectoryAlexandrea J. Ravenelle
- 6[Algorithmic Management, Employment, and the Self in Gig Work](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-6/type/BOOK_PART#CN-bp-6)Julia Tomassetti
- 7[Regulating Transportation Systems without Authority (or Data)](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-7/type/BOOK_PART#CN-bp-7)Plugging an Uber- and Lyft-Sized Hole in City Transportation Planning and PolicyZak Accuardi
    - San Fran. County case study
- 8[Words Matter](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-8/type/BOOK_PART#CN-bp-8)How Tech Media Helped Write Gig Companies into ExistenceSam Harnett
- 9[Rewriting the Rules](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-9/type/BOOK_PART#CN-bp-9)Gig Companies’ Drive for Labor DeregulationRebecca Smith and Maya Pinto
- 10[What Regulators Could Gain by Listening to Rideshare Drivers](https://www.cambridge.org/core/product/identifier/9781108767910%23CN-bp-10/type/BOOK_PART#CN-bp-10)Harry Campbell
    - RideshareGuy

**Comment by thin-lizard** [comment]
@nniiicc  -- For Friday 11/15, I suggest we read: 
- Ch 1. for an overview on "gig company" regulation in the US at the federal, state, and municipal levels - Some of it is familiar, but can still be useful for our framing of municipal policy 
- Ch 5. because it addresses the long-term implications of doing gig work - judging by a quick skim, it ties back to what we've discussed around moral injury, and workers' views of their other jobs / employers

**Comment by thin-lizard** [comment]
@lindseysschwartz - next set of readings will be for 12/02

**Comment by thin-lizard** [comment]
@nniiicc -- for Friday 12/02, I suggest we read:

- Ch 7 - for background on TNC operations in cities, and a case study describing a collaboration between San Francisco County Transit Authority and researchers at Northeastern to collect data on TNC use in San Francisco 
- The article published by the research team: https://journals.sagepub.com/doi/10.1177/0361198118798459 - I think it's worth looking at as a differing approach, and as a case for the fair/fare project

**Comment by nniiicc** [comment]
Notes on article 2:
- Use this as a primer for anyone who wants to work on the Fair!=Fare 
- Should submit our paper to the same journal
- If we think about extracting attributes of data used in FARE papers - what should we extract?
- - Limitations with approach 
- - Data source 
- - Description of resolution, cleaning, imputing null values, etc 
- - Something about its FAIRNESS ? (there must be a FAIR assessment tool or framework)

**Comment by nniiicc** [comment]
For the following week's reading: https://journals.sagepub.com/doi/pdf/10.1177/15356841211066931 
(very good fodder for our Gigplat 3 paper too)
