### ISSUE TITLE
The Handbook of Digital Labor

### ISSUE THREAD

**Issue by thin-lizard** [BITS-Research/GigPlatRevisit#42]
- https://iamcr.org/publications/iamcr-handbook
- https://iamcr.org/publications/iamcr-handbook/handbook-of-political-economy-of-communications

**Comment by thin-lizard** [comment]
For Friday 04/07 - we will each bring a pitch on one of the following: 

- Regulating the gig economy 
- Moral injury in digital labor 
- Organizing against Algorithmic Management 
- Information Asymmetries in the Gig Economy
- How solidarity politics emerge in decentralized work
- Worker owned cooperatives in digital labor

Think of:
- why is this topic important to consider in the context of digital labor 
- include 5 key publications 
- international scope

**Comment by thin-lizard** [comment]
LS pitch - Organizing Against Alg Management // Solidarity Politics in Decentralized Work - https://docs.google.com/document/d/172CF2NhuXA6dO0ptLSHBWr_yI4q2OfOqxFUXGuzobco/edit 

I think these are closely related so I brainstormed them together

**Comment by nniiicc** [comment]
NW - Moral Injury in Digital Labor https://docs.google.com/document/d/1h95oNAIBcnH9aF2gk16mlwysTDIIVCOpKNH984pAmdw/edit?usp=sharing

**Comment by thin-lizard** [comment]
For Wed 04.12 - we will each bring a 200 word draft abstract

**Comment by thin-lizard** [comment]
From the original email:

We'd like to call for chapter submissions to The Handbook of Digital Labor,
which we are editing for the Global Handbooks in Media & Communication
Research Series, an initiative under the International Association for
Media and Communication Research (IAMCR), to be published by Wiley.

Despite the generic title, we designed this handbook to chart rapidly
changing global labor conditions, challenge boundaries between “online” vs
“off-line” labor, and be a resource book that addresses key debates
surrounding perennial and urgent concerns about labor questions in
contemporary capitalism from a global perspective. While this handbook will
build on existing work, it stresses the reconceptualization of digital
labor in various contexts, connecting them across the sectors and
generations, and is intended to contribute to structural analysis and
intellectual praxis toward emancipatory movements.

This handbook is organized around four themes that are defined
historically, technologically, and internationally in the realms of work
and control, solidarity politics, pedagogy, and imaginaries:

1. Labor Under Capitalism

2. Digital Technologies, Work and Control

3. Solidarity Politics and the Working-Class Majority

4. Pedagogy, Imaginary and Emancipation

In this project, we investigate foundational labor questions as well as
emerging and/or persistent patterns of labor and labor organization under
new conditions such as digital platforms, automation, artificial
intelligence (AI), the ”gig” economy, new divisions of labor, and
alternative developments.
